import awash from './assets/ethioc/awash.jpeg'
import bale from './assets/ethioc/bale.jpeg'
import axum from './assets/ethioc/axum.jpeg'
import g from './assets/ethioc/Gheralta.jpeg'
import gonder from './assets/ethioc/gonder.jpeg'
export default [

    {title: "Awash National Park",map: "https://www.google.com/maps/place/Awash+National+Park/@9.0833333,40,15z/data=!4m6!3m5!1s0x164a756356c51cf1:0xae9bde25595552f8!8m2!3d9.0833333!4d40!16zL20vMDc3c2R0?entry=ttu", location: "Adama / Didiga", des: "This scenic national park is situated in the dry acacia savanna of the Rift Valley some 200km from Addis Ababa. A magnificent 150m-deep gorge, carved by the Awash River, forms the southern boundary of the park, including a substantial waterfall. To the north, you'll see the ragged edges of Mount Fantelle, a dormant volcano whose crater towers above the surrounding bush. ",img: {awash} },
    {title: "Axum",map: "https://www.google.com/maps/place/Aksum/@14.1325335,38.705305,13z/data=!3m1!4b1!4m6!3m5!1s0x166bfcbea0c26cfb:0x74d0dc83a015ace1!8m2!3d14.1340317!4d38.7472905!16zL20vMDF0Mmc4?entry=ttu", location: "Tigray", des: "This fascinating town was the centre of the Axumite Empire, one of the most important and technologically advanced civilisations of its time and a major force in world trade between the 1st and 7th centuries AD.",img: {axum} },
    {title: "Bale Mountains National Park",map: "https://www.google.com/maps/search/bale+mountains+national+park/@6.9105106,39.6897019,14z/data=!3m1!4b1?entry=ttu", location: "Shashemene", des: "The Bale Mountains National Park is a protected area of approximately 2,200 km2 and is located around 400 km southeast of Addis Ababa. Its high mountains, sweeping valleys, dramatic escarpment and wide expanses of forests provide visitors with a diversity of vistas unique to the Ethiopian highlands. ",img: {bale} },
    {title: "Gheralta",map: "https://www.google.com/maps/place/Nahiso+Terara/@13.8255545,39.2624131,14z/data=!3m1!4b1!4m6!3m5!1s0x166ba04c3f915521:0x198f4a5cec42db19!8m2!3d13.8255556!4d39.2830556!16s%2Fg%2F11cn34cvms?entry=ttu", location: "Northern Tigray", des: "This unspoilt corner of North Eastern Tigray is scenically spectacular with vast spaghetti-western landscapes of flat dry plains and towering rock outcrops known as the Gheralta. The region is most famous for its 35 old rock-hewn churches, the largest concentration anywhere in Ethiopia. The finest are found in splendid isolation on the outcrops and involving a strenuous walk, and the magnificent views, atmospheric interiors and a wealth of old paintings and church treasures are very special indeed.",img: {g} },
    {title: "Gonder city",map: "https://www.google.com/maps/place/Gondar/@12.6011268,37.4358056,14z/data=!3m1!4b1!4m6!3m5!1s0x164328823d244edf:0x7826245358a8a65!8m2!3d12.6030181!4d37.4521319!16zL20vMDN5bm53?entry=ttu", des: "Up until the beginning of the 17th century, Ethiopia had what was locally referred to as a 'mobile capital'. But in 1632 Fasilidas took the throne and proclaimed Gonder as his capital, where it remained for the next 200 years. As king and emperor Fasilidas not only ushered in a period of relative calm in Abyssinia's turbulent history he also built a stupendous fort at this strategic location - added to by his successors - most of which is still intact. Wandering around the fort's spectacular turreted citadels, vast banqueting halls and bathhouses leaves you in no doubt whatsoever as to the importance of this Christian kingdom 400 years ago.", location: "Gonder",img: {gonder} }


]